import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import en from "../../locales/en";
import ar from "../../locales/ar";
import Form from "../components/Form.jsx";
import ImageSection from "../sections/home/ImageSection.jsx";
import ContactPaySection from "../sections/home/ContactPaySection.jsx";
import IconsSection from "../sections/home/IconsSection.jsx";
import CoverSection from "../sections/home/CoverSection.jsx";
import PageCover from "@/components/PageCover";
import VerticalCarousel from "../components/VerticalCarousel.jsx";
import { Box } from "@mui/material";
import MemberCard from "@/components/MemberCard";
import PlaceCard from "@/components/PlaceCard";
import ReviewCard from "@/components/ReviewCard";
import IconTitle from "../components/mini-components/IconTileSection.jsx";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ------------------------------
  const router = useRouter();
  const { locale } = router;
  const t = locale === "en" ? en : ar;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CoverSection></CoverSection>
        <ImageSection></ImageSection>
        <IconsSection></IconsSection>
        <VerticalCarousel
          itemsArray={t.general.reviews}
          Component={ReviewCard}
          slidesPerView={4.3}
        ></VerticalCarousel>
        <ContactPaySection></ContactPaySection>
      </main>
    </>
  );
}
