import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import en from "../../locales/en";
import ar from "../../locales/ar";
import BottomCard from "../components/BottomCard.jsx";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ------------------------------
  const router = useRouter();
  const { locale } = router;
  const t = locale === "en" ? en : ar;
  // ------------------------------
  // const changeLanguage = (e) => {
  //   const locale = e.target.value;
  //   router.push(router.pathname, router.asPath, { locale });
  // };
  const toAr = () => {
    const locale = "ar";
    router.push(router.pathname, router.asPath, { locale });
  };
  const toEn = () => {
    const locale = "en";
    router.push(router.pathname, router.asPath, { locale });
  };
  // -------------------------------
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>Home</>
        {/* <Paragraph
          img="/test.png"
          title="title title"
          body="body body body body body body body body"
          orientation={1}
          textStyle={{ textAlign: "center" }}
        /> */}
        <BottomCard></BottomCard>
        <button onClick={toAr}>AR</button>
        <button onClick={toEn}>EN</button>
        <p className="my-8"> {}</p>
      </main>
    </>
  );
}
