import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import en from "../../locales/en";
import ar from "../../locales/ar";
import Card from "../components/aboutCard/aboutCard";
import ProductCard from "../components/productCard/card";
import Statistics from "../components/statistics/statistics";

import { Box } from "@mui/material";
import Calcuation from "@/components/calculation/calculation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // ------------------------------
  const router = useRouter();
  const { locale } = router;
  const t = locale === "en" ? en : ar;
  // ------------------------------
  // const changeLanguage = (e) => {
  //   const locale = e.target.value;
  //   router.push(router.pathname, router.asPath, { locale });
  // };
  const toAr = () => {
    const locale = "ar";
    router.push(router.pathname, router.asPath, { locale });
  };
  const toEn = () => {
    const locale = "en";
    router.push(router.pathname, router.asPath, { locale });
  };
  // -------------------------------
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: "flex",
          my: 5,
          flexDirection: {
            xs: "column",
            md: "row",
          },
        }}
      >
        <Card
          icon="/images/eye.png"
          heading={t.about.card.visionTitle}
          textArr={t.about.card.visionText}
        />
        <Card
          icon="/images/mission.png"
          heading={t.about.card.missionTitle}
          textArr={t.about.card.missionText}
        />
        <Card
          icon="/images/value.png"
          heading={t.about.card.valueTitle}
          textArr={t.about.card.valueText}
        />
      </Box>
      <Box
        sx={{
          display: "flex",
          my: 5,
          flexDirection: {
            xs: "column",
            md: "row",
          },
        }}
      >
        <Statistics
          num={360}
          suffix={t.about.statistic.sufTheous}
          text={t.about.statistic.process}
        />
        <Statistics
          num={150}
          suffix={t.about.statistic.sufTheous}
          text={t.about.statistic.client}
        />
        <Statistics num={2200} suffix="" text={t.about.statistic.emp} />
      </Box>
      <Box
        className="horizontal-safe-padding  vertical-safe-margin "
        sx={{
          display: "flex",
          my: 5,
          flexDirection: {
            xs: "column",
            sm: "row",
          },
        }}
      >
        <ProductCard
          title={"الاقتصادي"}
          textArr={[
            "مقدم يبدأ من 20%",
            "التأمين اجباري",
            "فترات سداد تصل الي 3 سنوات",
          ]}
          bgcolor="#1169a8"
        />
        <ProductCard
          title={"الاقتصادي"}
          textArr={[
            "مقدم يبدأ من 20%",
            "التأمين اجباري",
            "فترات سداد تصل الي 3 سنوات",
          ]}
          bgcolor="#1169a8"
        />
      </Box>
      <Calcuation />
    </>
  );
}
